#################################################################
#                                                               #
#                   Packages/Xiaomi Status                      #
#                                                               #
#################################################################
        

  
#################################################################
#   Group                                                       #
#################################################################

group:
  xiaomi_door_sensors:
    name: Door Sensors
    #view: no
    entities:
      - binary_sensor.front_door_sensor # דלת כניסה
      - binary_sensor.balcony_door_sensor # דלת מרפסת
      - binary_sensor.washing_machine_sensor # מכונסת כביסה
      - binary_sensor.laundry_dryer_sensor # מייבש כביסה
      - binary_sensor.air_conditioner_yakir # דלת מזגן חדר של יקיר
      
  xiaomi_motion_sensors:
    name: Motion Sensors
    #view: no
    entities:
      - binary_sensor.main_shower_motion_sensor # חיישן תנועה מקלחת
      - binary_sensor.parents_shower_motion_sensor # חיישן תנועה מקלחת הורים
      - binary_sensor.guest_bathrom_motion_sensor # חיישן תנועה מקלחת ראשית
      - binary_sensor.laundry_room_motion_sensor # חיישן תנועה חדר כביסה
      
#################################################################
#   Binary Sensors                                              #
#################################################################

binary_sensor:

####################################################
#   Binary Sensor - Template                       #
####################################################

  - platform: template
    sensors:
## Door Sensors
      front_door:
        friendly_name: Front Door Sensor
        device_class: connectivity
        entity_id: sensor.front_door
        value_template: "{{ is_state('sensor.front_door', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.front_door', 'on') %}
            mdi:door-open
          {% elif is_state('sensor.front_door', 'off') %}
            mdi:door-closed       
          {% else %}
            mdi:alert
          {% endif %}
          
      balcony_door:
        friendly_name: Exit Door to balcony
        device_class: connectivity
        entity_id: sensor.balcony_door
        value_template: "{{ is_state('sensor.balcony_door', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.balcony_door', 'on') %}
            mdi:door-closed
          {% elif is_state('sensor.balcony_door', 'off') %}
            mdi:door-open         
          {% else %}
            mdi:alert
          {% endif %}
          
      # washing_machine:
      #   friendly_name: Washing machine
      #   device_class: connectivity
      #   entity_id: sensor.washing_machine
      #   value_template: "{{ is_state('sensor.washing_machine', 'on') }}"
      #   icon_template: >-
      #     {% if is_state('sensor.washing_machine', 'on') %}
      #       mdi:door-closed
      #     {% elif is_state('sensor.washing_machine', 'off') %}
      #       mdi:door-open         
      #     {% else %}
      #       mdi:alert
      #     {% endif %}   
          
      laundry_dryer:
        friendly_name: Laundry Dryer
        device_class: connectivity
        entity_id: sensor.washing_machine
        value_template: "{{ is_state('sensor.laundry_dryer', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.laundry_dryer', 'on') %}
            mdi:door-closed
          {% elif is_state('sensor.laundry_dryer', 'off') %}
            mdi:door-open         
          {% else %}
            mdi:alert
          {% endif %}          

## Motion Sensors
      motion_shower:
        friendly_name: Motion sensor Main Shower
        device_class: connectivity
        entity_id: sensor.motion_shower
        value_template: "{{ is_state('sensor.motion_shower', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.motion_shower', 'on') %}
            mdi:walk
          {% elif is_state('sensor.motion_shower', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %}

      bedroom_motion:
        friendly_name: Bedroom sensor
        device_class: connectivity
        entity_id: sensor.bedroom_motion
        value_template: "{{ is_state('sensor.bedroom_motion', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.bedroom_motion', 'on') %}
            mdi:walk
          {% elif is_state('sensor.bedroom_motion', 'off') %}
            mdi:walk        
          {% else %}
            mdi:alert
          {% endif %}

      main_shower:
        friendly_name: Main Shower
        device_class: connectivity
        entity_id: sensor.main_shower
        value_template: "{{ is_state('sensor.main_shower', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.main_shower', 'on') %}
            mdi:walk
          {% elif is_state('sensor.main_shower', 'off') %}
            mdi:walk        
          {% else %}
            mdi:alert
          {% endif %}          

      guest_services:
        friendly_name: Guest Services Motion Sensor
        device_class: connectivity
        entity_id: sensor.guest_services
        value_template: "{{ is_state('sensor.guest_services', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.guest_services', 'on') %}
            mdi:walk
          {% elif is_state('sensor.guest_services', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %} 
          
      computer_room:
        friendly_name: Motion Sensor Computer Room
        device_class: connectivity
        entity_id: sensor.computer_room
        value_template: "{{ is_state('sensor.computer_room', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.computer_room', 'on') %}
            mdi:walk
          {% elif is_state('sensor.computer_room', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %} 

      laundry_room:
        friendly_name: Motion Sensor Laundry Room
        device_class: connectivity
        entity_id: sensor.laundry_room
        value_template: "{{ is_state('sensor.laundry_room', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.laundry_room', 'on') %}
            mdi:walk
          {% elif is_state('sensor.laundry_room', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %} 



## Temperature Sensors
                  
      living_room_temperature:
        friendly_name: Temp Living Room
        device_class: connectivity
        entity_id: sensor.living_room_temp_sensor
        value_template: "{{ is_state('sensor.living_room_temp_sensore_rature', 'on') }}"
        icon_template: >-
          {% if is_state('sensor.living_room_temp_sensore_rature', 'on') %}
            mdi:walk
          {% elif is_state('sensor.living_room_temp_sensore_rature', 'off') %}
            mdi:walk         
          {% else %}
            mdi:alert
          {% endif %}           
          

      # second_floor_temperature:
      #   friendly_name: Temp in second floor
      #   device_class: connectivity
      #   entity_id: sensor.second_floor_temperature
      #   value_template: "{{ is_state('sensor.second_floor_temperature', 'on') }}"
      #   icon_template: >-
      #     {% if is_state('sensor.second_floor_temperature', 'on') %}
      #       mdi:walk
      #     {% elif is_state('sensor.second_floor_temperature', 'off') %}
      #       mdi:walk         
      #     {% else %}
      #       mdi:alert
      #     {% endif %}           

#################################################################
#  Sensors                                                      #
#################################################################

sensor:

####################################################
#   Sensor - Template                              #
####################################################

  - platform: template
    sensors:
## Door Sensors
      front_door:
        friendly_name: "Front Door"
        value_template: >-
          {% if is_state('binary_sensor.front_door_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.front_door_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}

      balcony_door:
        friendly_name: "Exit Door to balcony"
        value_template: >-
          {% if is_state('binary_sensor.balcony_door_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.balcony_door_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}

      # washing_machine:
      #   friendly_name: "Washing Machine"
      #   value_template: >-
      #     {% if is_state('binary_sensor.washing_machine_sensor', 'on') %}
      #       on
      #     {% elif is_state('binary_sensor.washing_machine_sensor', 'off') %}
      #       on
      #     {% else %}
      #       off
      #     {% endif %} 
          
      laundry_dryer:
        friendly_name: "Laundry Dryer"
        value_template: >-
          {% if is_state('binary_sensor.laundry_dryer_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.laundry_dryer_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %} 
          
      air_conditioner_yakir_door:
        friendly_name: "Air Conditioner Yakir door"
        value_template: >-
          {% if is_state('binary_sensor.air_conditioner_yakir', 'on') %}
            on
          {% elif is_state('binary_sensor.air_conditioner_yakir', 'off') %}
            on
          {% else %}
            off
          {% endif %}           

      laundry_dryer_status:
        friendly_name: "דלת מייבש"
        entity_id: binary_sensor.laundry_dryer_sensor
        value_template: >-
          {% if is_state('binary_sensor.laundry_dryer_sensor', 'on') %}
            Open
          {% elif is_state('binary_sensor.laundry_dryer_sensor', 'off') %}
            Closed
          {% endif %}
          
      # washing_machine_status:
      #   friendly_name: "דלת מכונת כביסה"
      #   entity_id: binary_sensor.washing_machine_sensor
      #   value_template: >-
      #     {% if is_state('binary_sensor.washing_machine_sensor', 'on') %}
      #       Open
      #     {% elif is_state('binary_sensor.washing_machine_sensor', 'off') %}
      #       Closed
      #     {% endif %}  
          
      air_conditioner_yakir_door_status:
        friendly_name: "מזגן יקיר"
        entity_id: binary_sensor.air_conditioner_yakir
        value_template: >-
          {% if is_state('binary_sensor.air_conditioner_yakir', 'on') %}
            Open
          {% elif is_state('binary_sensor.air_conditioner_yakir', 'off') %}
            Closed
          {% endif %}            
          

## Motion Sensors
      motion_shower:
        friendly_name: "Motion sensor Main Shower"
        value_template: >-
          {% if is_state('binary_sensor.main_shower_motion_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.main_shower_motion_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}          

      bedroom_motion:
        friendly_name: "Bedroom sensor"
        value_template: >-
          {% if is_state('binary_sensor.parents_shower_motion_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.parents_shower_motion_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}           
          
      main_shower:
        friendly_name: "Main Shower"
        value_template: >-
          {% if is_state('binary_sensor.main_shower_motion_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.main_shower_motion_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}
          

      guest_services:
        friendly_name: "Guest Services Motion Sensor"
        value_template: >-
          {% if is_state('binary_sensor.guest_bathrom_motion_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.guest_bathrom_motion_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}


      computer_room:
        friendly_name: "Motion Sensor Computer Room"
        value_template: >-
          {% if is_state('binary_sensor.server_room_motion_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.server_room_motion_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}

      laundry_room:
        friendly_name: "Motion Sensor Laundry Room"
        value_template: >-
          {% if is_state('binary_sensor.laundry_room_motion_sensor', 'on') %}
            on
          {% elif is_state('binary_sensor.laundry_room_motion_sensor', 'off') %}
            on
          {% else %}
            off
          {% endif %}