- platform: mqtt  
  name: "Server Room Fan"
  state_topic: "stat/fan/POWER"
  command_topic: "cmnd/fan/POWER"
  availability_topic: "tele/fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 
