#################################################################
#                                                               #
#                      Packages/Cameras                         #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                          cameras                              #
#                                                               #
#################################################################
camera:


#################################################################
#                        Blue iris                              #
#################################################################
    - platform: mjpeg
      mjpeg_url: !secret hostcenter
      name: Center 6MP
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic
      
    - platform: mjpeg
      mjpeg_url: !secret building
      name: Entrance to the Building
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic   
      
    - platform: mjpeg
      mjpeg_url: !secret door
      name: Front Door
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic       
 
    - platform: mjpeg
      mjpeg_url: !secret right_side_balcony
      name: Right Side Balcony
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic  
  
    - platform: mjpeg
      mjpeg_url: !secret xiaomi_dafang
      name: Xiaomi Dafang
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic      

#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
group:
  Outside the home:
    name: Outside Camera
    view: no
    entities:
      - camera.entrance_to_the_building
      - camera.right_side_balcony
      - camera.center_6mp


  inside the home:
    name: Home Fornt Dor Camera 
    view: no
    entities:
      - camera.front_door
      - camera.xiaomi_dafang
    
    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:
  - alias: frontdoor_snapshot
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 'binary_sensor.door_window_sensor_158d0001ef3425'
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.avi_avi'
          state: 'not_home'
        - condition: state
          entity_id: 'device_tracker.nurit_iphone' # מכוון לספק מידע דרך הראוטר - אמין יותר בשביל 
          state: 'not_home'
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.front_door
          filename: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
      - service: notify.avitelegram
        data:
          title: "Home Aׁssistant"
          message: "מישהו לא מורשה פתח את הדלת"
          data:
            photo:
              - file: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
                capture: Front House Camera              


########################### 
  - alias: 'turn off xiaomi dafang camera if nurit at home'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.nurit_iphone
      to: 'home'
      for:
        minutes: 1
        seconds: 30
    action:
      - service: switch.turn_off
        entity_id: switch.sh20_pow

      - service: notify.mobile_app_nurit_iphone
        data:
          title: "אבטחה"
          message: 'ברוכה הבאה נורית, המצלמה כבויה'


##########################          
  - alias: 'turn on xiaomi dafang camera if nurit not at home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.nurit_iphone
        to: 'not_home'
        for:
          minutes: 1
    action:
      - service: switch.turn_on
        entity_id: switch.sh20_pow
      - service: notify.avitelegram
        data:
          title: "Home Aׁssistant"
          message: 'נורית לא בבית, המצלמה דולקת'
              
########################## 
  - alias:  'turn off xiaomi dafang camera if morning and we are at home'
    initial_state: 'on'
    trigger:
      platform: time
      at: '07:00:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.nurit_iphone
          state: 'home'

    action:
      - service: homeassistant.turn_off
        entity_id: switch.sh20_pow
      - service: notify.avitelegram
        data:
          title: "Home Aׁssistant"
          message: 'אתם בבית - המצלמה נסגרה, אין צורך '        


    #########################  Camera  ##########################        

  - alias: turn on xiaomi camera in 23:00
    initial_state: 'on'  
    trigger:
      platform: time
      at: '23:00:00'

    action:
      - service: automation.turn_off 
        data:
          entity_id: automation.turn_off_xiaomi_dafang_camera_if_nurit_at_home
          
      - service: homeassistant.turn_on
        entity_id: switch.sh20_pow
        
      - service: notify.avitelegram
        data:
          title: "Home Aׁssistant"  
          message: 'השעה 23:00 המצלמות דולקות'

          

# ##########################          
#   - alias:  Turn on Xiaomi Dafang camera if avi not at home
#     initial_state: 'on'
#     trigger:
#       - platform: state
#         entity_id: device_tracker.life360_avi_abeksis
#         to: 'not_home'
#         for:
#           minutes: 1
#     condition:
#       condition: and
#       conditions:
#         - condition: state
#           entity_id: device_tracker.life360_avi_abeksis
#           state: 'not_home'
#     action:
#       - service: homeassistant.turn_on
#         entity_id: switch.sh20_pow        

############################
#   - alias:  Turn off Xiaomi Dafang if avi at home
#     initial_state: 'on'
#     trigger:
#       platform: state
#       entity_id: device_tracker.avi_avi
#       to: 'home'
#       for:
#         minutes: 1
#         seconds: 30
#     action:
#       - service: homeassistant.turn_off
#         entity_id: switch.sh20_pow 

#       - service: notify.avitelegram
#         data:
#           title: "אבטחה"
#           message: 'ברוך הבא אבי, המצלמה כבויה' 

