#################################################################
#                                                               #
#                      Packages/Cameras                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:      

    ## שינוי שמות לאוטומציה של כיבוי המצלמה ##
    automation.turn_on_xiaomi_cameras_if_nurit_and_avi_not_at_home:
      friendly_name: פעיל - אני ונורית לא בבית
      icon: mdi:cctv
      home_assistant: true
      
    automation.turn_off_xiaomi_cameras_if_avi_at_home:
      friendly_name: כיבוי מצלמה - אבי בבית
      icon: mdi:cctv
      home_assistant: true
      
    automation.turn_off_xiaomi_dafang_camera_if_nurit_at_home:
      friendly_name: כיבוי מצלמה - נורית בבית
      icon: mdi:cctv
      home_assistant: true

    automation.turn_on_cctv_cameras_if_late_night:
      friendly_name: פעיל - מצלמה פעילה 23:00
      icon: mdi:cctv
      home_assistant: true

    automation.turn_off_xiaomi_dafang_camera_if_morning_and_we_are_at_home:
      friendly_name: כיבוי מצלמה 7 בבוקר
      icon: mdi:cctv
      home_assistant: true

    # automation.avi_wifi_off:
    #   friendly_name: הפעלת מצלמת שיאומי - וויפי אבי מכובה
    #   icon: mdi:wifi-off
    #   home-assistant: true

    # automation.avi_wifi_on:
    #   friendly_name: כיבוי מצלמת שיאומי - וויפי אבי פעיל
    #   icon: mdi:wifi
    #   home-assistant: true  

    # automation.nurit_wifi_off:
    #   friendly_name: הפעלת מצלמת שיאומי - וויפי נורית מכובה
    #   icon: mdi:wifi-off
    #   home-assistant: true  

    # automation.nurit_wifi_on:
    #   friendly_name: כיבוי מצלמת שיאומי - וויפי נורית פעיל
    #   home-assistant: true

    # automation.yakir_wifi_off:    
    #   friendly_name: זיהוי מצב ה וויפי של יקיר - לא זמין
    #   icon: mdi:wifi-off
    #   home-assistant: true

    # automation.yakir_wifi_on:
    #   friendly_name: זיהוי מצב ה וויפי של יקיר - זמין
    #   icon: mdi:wifi
    #   home-assistant: true


#################################################################
#                                                               #
#                          cameras                              #
#                                                               #
#################################################################
camera:


#################################################################
#                        Blue iris                              #
#################################################################
    - platform: mjpeg
      mjpeg_url: !secret hostcenter
      name: Center 6MP
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic
      
    - platform: mjpeg
      mjpeg_url: !secret building
      name: Entrance to the Building
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic   
      
    - platform: mjpeg
      mjpeg_url: !secret door
      name: Front Door
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic       
 
    - platform: mjpeg
      mjpeg_url: !secret right_side_balcony
      name: Right Side Balcony
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic  
  
    - platform: mjpeg
      mjpeg_url: !secret xiaomi_dafang
      name: Xiaomi Dafang
      username: !secret bi_username
      password: !secret bi_password
      authentication: basic      

#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
group:
  Outside the home:
    name: Outside Camera
    view: no
    entities:
      - camera.entrance_to_the_building
      - camera.right_side_balcony
      - camera.center_6mp


  inside the home:
    name: Home Fornt Dor Camera 
    view: no
    entities:
      - camera.front_door
      - camera.xiaomi_dafang
    
    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:
  - alias: frontdoor_snapshot
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: 'binary_sensor.door_window_sensor_158d0001ef3425'
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.avi_avi'
          state: 'not_home'
        - condition: state
          entity_id: 'device_tracker.nurit_iphone' # מכוון לספק מידע דרך הראוטר - אמין יותר בשביל 
          state: 'not_home'
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.front_door
          filename: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
      # - delay: 
      #   seconds: 5
      - service: notify.avitelegram
        data:
          title: "הדלת נפתחה"
          message: "מישהו לא מורשה פתח את הדלת"
          data:
            photo:
              - file: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
                capture: Front House Camera              

############################
#   - alias:  Turn off Xiaomi Dafang if avi at home
#     initial_state: 'on'
#     trigger:
#       platform: state
#       entity_id: device_tracker.avi_avi
#       to: 'home'
#       for:
#         minutes: 1
#         seconds: 30
#     action:
#       - service: homeassistant.turn_off
#         entity_id: switch.sh20_pow 

#       - service: notify.avitelegram
#         data:
#           title: "אבטחה"
#           message: 'ברוך הבא אבי, המצלמה כבויה' 

########################### 
  - alias:  Turn off Xiaomi Dafang camera if nurit at home
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.nurit_iphone # מכוון לספק מידע דרך הראוטר - אמין יותר בשביל 
      to: 'home'
      for:
        minutes: 1
        seconds: 30
    action:
      - service: homeassistant.turn_off
        entity_id: switch.sh20_pow

      - service: notify.mobile_app_nurit_iphone
        data:
          title: "אבטחה"
          message: 'ברוכה הבאה נורית, המצלמה כבויה'
          data:
            push:
              sound: "US-EN-Alexa-Welcome-Home.wav"
              badge: 5
              category: 'modifymycctvswitch'
            attachment: 
              url: http://cdn2.iconfinder.com/data/icons/forbidden-signs/512/forbidden_record_video-512.png
              
########################## 
  - alias:  Turn off Xiaomi Dafang camera if Morning and we are at home
    initial_state: 'on'
    trigger:
      platform: time
      at: '07:00:00'
    condition:
      condition: or
      conditions:
        # - condition: state
        #   entity_id: device_tracker.avi_avi
        #   state: 'home'
        - condition: state
          entity_id: device_tracker.nurit_iphone # מכוון לספק מידע דרך הראוטר - אמין יותר בשביל 
          state: 'home'

    action:
      - service: homeassistant.turn_off
        entity_id: switch.sh20_pow
      - service: notify.avitelegram
        data:
          title: "אבטחה"
          message: 'אתם בבית - המצלמה נסגרה, אין צורך '        
          

          
##########################          
  - alias:  Turn on Xiaomi Dafang camera if nurit and avi not at home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.avi_avi,device_tracker.iphone_nurit
        to: 'not_home'
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.avi_avi
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.nurit_iphone # מכוון לספק מידע דרך הראוטר - אמין יותר בשביל האוטומציה
          state: 'not_home'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.sh20_pow