#################################################################
#                                                               #
#                     Packages/Appliances                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.robovac_cleaning_time:
      icon: mdi:clock-outline
    sensor.robovac_main_brush:
      icon: mdi:blender
    sensor.robovac_side_brush:
      icon: mdi:blender
    sensor.robovac_filter:
      icon: mdi:filter
    sensor.robovac_cleaning_count:
      icon: mdi:counter
      
#################################################################
#                                                               #
#                            Groups                             #
#                                                               #
#################################################################      
      
group:

  robovac:
    name: Robovac
    view: no
    control: hidden 
    entities:
      - vacuum.robovac  
      - sensor.robovac_status 
      - sensor.robovac_battery
      - sensor.robovac_cleaning_time
      - sensor.robovac_main_brush
      - sensor.robovac_side_brush
      - sensor.robovac_filter
      - sensor.robovac_cleaning_count      



#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################  

sensor:

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors:

## Robovac Things
      robovac_status:
        friendly_name: "Status"
        value_template: "{{ states.vacuum.robovac.attributes.status }}"
        icon_template: >-
          {% if is_state('sensor.robovac_status', 'Cleaning') %}
            mdi:robot-vacuum
          {% elif is_state('sensor.robovac_status', 'Returning home') %}
            mdi:home
          {% elif is_state('sensor.robovac_status', 'Charging') %}
            mdi:battery-charging-wireless
          {% elif is_state('sensor.robovac_status', 'Idle') %}
            mdi:sleep
          {% elif is_state('sensor.robovac_status', 'Error') %}
            mdi:alert
          {% elif is_state('sensor.robovac_status', 'Charger disconnected') %}
            mdi:power-plug-off
          {% else %}
            mdi:help-circle
          {% endif %}
      robovac_battery:
        friendly_name: "Battery"
        unit_of_measurement: "%"
        device_class: battery
        value_template: "{{ states.vacuum.robovac.attributes.battery_level }}"
      robovac_cleaning_time:
        friendly_name: "Cleaning Time"
        unit_of_measurement: "Mins"
        value_template: "{{ states.vacuum.robovac.attributes.cleaning_time }}"
      robovac_main_brush:
        friendly_name: "Main Brush Left"
        unit_of_measurement: "Hrs"
        value_template: "{{ states.vacuum.robovac.attributes.main_brush_left }}"
      robovac_side_brush:
        friendly_name: "Side Brush Left"
        unit_of_measurement: "Hrs"
        value_template: "{{ states.vacuum.robovac.attributes.side_brush_left }}"
      robovac_filter:
        friendly_name: "Filter Left"
        unit_of_measurement: "Hrs"
        value_template: "{{ states.vacuum.robovac.attributes.filter_left }}"
      robovac_cleaning_count:
        friendly_name: "Cleaning Count"
        value_template: "{{ states.vacuum.robovac.attributes.cleaning_count }}"
      robovac_cleaned_area:
        friendly_name: "Cleaned Area"
        value_template: "{{ states.vacuum.robovac.attributes.cleaned_area }}"
      robovac_total_clean_time:
        friendly_name: "Total Clean Time"
        unit_of_measurement: "Mins"
        value_template: "{{ states.vacuum.robovac.attributes.total_cleaning_time }}"
      robovac_sensor_dirty:
        friendly_name: "Dirty Sensor"
        unit_of_measurement: "Hrs"
        value_template: "{{ states.vacuum.robovac.attributes.sensor_dirty_left }}"

  - platform: template
    sensors:
      vacuum_cleaner_error_sensor:
        friendly_name: Vacuum Cleaner Error Sensor
        value_template: >-
          {% if states.vacuum.robovac.attributes.error is defined %}
            {{states.vacuum.robovac.attributes.error}}
          {% else %}
            No Error
          {% endif %}
          
  - platform: template
    sensors:
      vacuum_cleaner_status_sensor:
        friendly_name: Vacuum Cleaner Status Sensor
        value_template: >-
          {{ states.vacuum.robovac.attributes.status }}

    
#################################################################
#                                                               #
#                           Vacuums                             #
#                                                               #
#################################################################

vacuum:

####################################################
#                                                  #
#                 Vacuums - Xiaomi                 #
#                                                  #
####################################################

  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token
    name: RoboVac

####################################################
#                                                  #
#                 Vacuums - input_select           #
#                                                  #
####################################################

input_select:
  xiaomi_vacuum:
    name: Xiaomi Vacuum
    options:
      - Quiet
      - Balanced
      - Turbo
      - Max
      - Mop

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

#################################################################
#   Vacuum                                                      #
#################################################################

  - id: vacuum_fan_speed_quiet
    alias: Vacuum Fan Speed Quiet
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Quiet'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.robovac
         fan_speed: 20
  
  - id: vacuum_fan_speed_balanced
    alias: Vacuum Fan Speed Balanced
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Balanced'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.robovac
         fan_speed: 50
  
  - id: vacuum_fan_speed_turbo
    alias: Vacuum Fan Speed Turbo
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Turbo'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.robovac
         fan_speed: 80
  
  - id: vacuum_fan_speed_max
    alias: Vacuum Fan Speed Max
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Max'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.robovac
         fan_speed: 100


  #################################################################
  #   Vacuum avitelegram                                          #
  #################################################################
  
  - id: vacuum_cleaner_error
    alias: Vacuum Cleaner Error
    trigger:
      - platform: state
        entity_id: vacuum.robovac
        to: 'Error'
      - platform: state
        entity_id: vacuum.robovac
        to: 'In Error'
      - platform: state
        entity_id: vacuum.robovac
        to: 'Charging Error'
    action:
      - service: notify.avi_telegram
        data:
          title: 'Roborock'
          message: >-
            {% if is_state('sensor.vacuum_cleaner_error_sensor', 'No Error')  %}
              {{states.sensor.vacuum_cleaner_status_sensor.state}}
            {% else %}
              {{states.sensor.vacuum_cleaner_error_sensor.state}}
            {% endif %}
  
  
  #################################################################
  #   Vacuum step                                                 #
  #################################################################  
  
  - id: vacuum_cleaner_started
    alias: Vacuum Cleaner Started
    trigger:
      - platform: state
        entity_id: vacuum.robovac
        to: 'cleaning'
      - platform: state
        entity_id: vacuum.robovac
        to: 'returning'
      - platform: state
        entity_id: vacuum.robovac
        to: 'docked'
      - platform: state
        entity_id: vacuum.robovac
        to: 'paused'
      - platform: state
        entity_id: vacuum.robovac
        to: 'idle'
    action:
      - service: notify.avi_telegram
        data:
          title: 'Roborock'
          message: >-
            {{states.sensor.vacuum_cleaner_status_sensor.state}}
