#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

      
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:
  # - platform: moon
  
## Weather Dark Sky
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - sunrise_time
      - sunset_time 
      - cloud_cover
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - minutely_summary
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5

####################################################
#                                                  #
#                     Weather                      #
#                                                  #
####################################################

sun:

  
