# Light Stars On/Off
automation.lighting_the_light_after_sunset_at_eleven_oclock:
  friendly_name: Lighting at sunset
  icon: mdi:white-balance-sunny

automation.lights_off_after_sunset:
  friendly_name: Turning off lighting at sunrise
  icon: mdi:brightness-6

# Tami 4
automation.auto_off_tami_4_in_night:
  friendly_name: Tammy 4 shutdown at Night
  icon: mdi:cup-water
  home-assistant: true

automation.turn_on_tami_4_in_mornning:
  friendly_name: Turning on Tammy 4 in the morning
  icon: mdi:cup-water
  home-assistant: true