#################################################################
#                                                               #
#                   Packages/Things Status                      #
#                                                               #
#################################################################


#################################################################
#   Group                                                       #
#################################################################
group:
  cameras:
    name: Cameras
    #view: no
    entities:
      # - sensor.front_door_camera_state
      - binary_sensor.dahua_camera
      - binary_sensor.building_foront_camera
      - binary_sensor.high_quality_camera

      
  smart_home:
    name: Smart Home
    #view: no
    entities:
      - binary_sensor.broadlink_remote
      - binary_sensor.google_home_mini
      
  wall_switches:
    name: Wall Switches
    #view: no
    entities:
      - binary_sensor.light_switch_poop
      - binary_sensor.wall_switch_prozdor
      - binary_sensor.wall_switch_laundry
      - binary_sensor.wall_switch_miklahat
      - binary_sensor.shutters    
      
  light_bulbs:
    name: Light Bulbs
   # view: no
    entities:
      - binary_sensor.sonoff_balcony_light
      - binary_sensor.sonoff_light_liran
      - binary_sensor.sonoff_service_balcony_light
      - binary_sensor.sonoff_stairs_light
      - binary_sensor.sonoff_bedroom_parents
      - binary_sensor.yeelinklightcolor1_miio86767262
      
  fan:
    name: Fan Sonoff
    #view: no
    entities:
      - binary_sensor.sonff_fan
      
  network_connection:
    name: Network connections
    #view: no
    entities:
      - binary_sensor.unifi_access_point
 


#################################################################
#   Sensors                                                     #
#################################################################

sensor:

####################################################
#                 Sensor - Template                #
####################################################

  - platform: template
    sensors:
    
      sensor_count:
        friendly_name: 'Number of Sensors'
        value_template: >
          {%- set domains = ['sensor'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      automation_count:
        friendly_name: 'Number of Automations'
        value_template: >
          {%- set domains = ['automation'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      script_count:
        friendly_name: 'Number of Scripts'
        value_template: >
          {%- set domains = ['script'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      switch_count:
        friendly_name: 'Number of Switches'
        value_template: >
          {%- set domains = ['switch'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      binary_sensor_count:
        friendly_name: 'Number of Binary Sensors'
        value_template: >
          {%- set domains = ['binary_sensor'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      lights_count:
        friendly_name: 'Number of Lights'
        value_template: >
          {%- set domains = ['light'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      tracker_count:
        friendly_name: 'Number of Devices'
        value_template: >
          {%- set domains = ['device_tracker'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      camera_count:
        friendly_name: 'Number of Devices'
        value_template: >
          {%- set domains = ['camera'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      fan_count:
        friendly_name: 'Number of Devices'
        value_template: >
          {%- set domains = ['fan'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      media_player_count:
        friendly_name: 'Number of Devices'
        value_template: >
          {%- set domains = ['media_player'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}
          
      plant_count:
        friendly_name: 'Number of Devices'
        value_template: >
          {%- set domains = ['plant'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}


      dahua_6m_camera_state:
        friendly_name: Dahua 6m
        entity_id: device_tracker.dahua_6m_camera
        value_template: >-
          {% if is_state('device_tracker.dahua_6m_camera', 'home') %}
            100
          {% elif is_state('device_tracker.dahua_6m_camera', 'not_home') %}
            0
          {% endif %} 
          
      front_door_camera_state:
        friendly_name: Front Door Camera
        entity_id: device_tracker.front_door_camera
        value_template: >-
          {% if is_state('device_tracker.front_door_camera', 'home') %}
            100
          {% elif is_state('device_tracker.front_door_camera', 'not_home') %}
            0
          {% endif %}    

      high_quality_camera_state:
        friendly_name: High Qualit Camera
        entity_id: device_tracker.high_quality_camera
        value_template: >-
          {% if is_state('device_tracker.high_quality_camera', 'home') %}
            100
          {% elif is_state('device_tracker.high_quality_camera', 'not_home') %}
            0
          {% endif %} 

      building_foront_camera_state:
        friendly_name: Front Building Camera
        entity_id: device_tracker.building_foront_camera
        value_template: >-
          {% if is_state('device_tracker.building_foront_camera', 'home') %}
            100
          {% elif is_state('device_tracker.building_foront_camera', 'not_home') %}
            0
          {% endif %}      
          
          
      miklahat_2732:
        friendly_name: Main shower
        entity_id: device_tracker.miklahat_2732
        value_template: >-
          {% if is_state('device_tracker.miklahat_2732', 'home') %}
            100
          {% elif is_state('device_tracker.miklahat_2732', 'not_home') %}
            0
          {% endif %}

      liran_light_switch_state:
        friendly_name: Liran Light Switch
        entity_id: device_tracker.liran_light_switch
        value_template: >-
          {% if is_state('device_tracker.liran_light_switch', 'home') %}
            100
          {% elif is_state('device_tracker.liran_light_switch', 'not_home') %}
            0
          {% endif %} 

      sonoff_bedroom_parents:
        friendly_name: Parents Bedroom
        entity_id: device_tracker.sonoff_bedroom_parents
        value_template: >-
          {% if is_state('device_tracker.sonoff_bedroom_parents', 'home') %}
            100
          {% elif is_state('device_tracker.sonoff_bedroom_parents', 'not_home') %}
            0
          {% endif %}


      laundry_light_switch_state:
        friendly_name: Laundry Light Switch
        entity_id: device_tracker.laundry_light_switch_switch
        value_template: >-
          {% if is_state('device_tracker.laundry_light_switch', 'home') %}
            100
          {% elif is_state('device_tracker.laundry_light_switch', 'not_home') %}
            0
          {% endif %}   

      broadlink_state:
        friendly_name: Broadlink State
        entity_id: device_tracker.broadlink
        value_template: >-
          {% if is_state('device_tracker.broadlink', 'home') %}
            100
          {% elif is_state('device_tracker.broadlink', 'not_home') %}
            0
          {% endif %} 
          

      sonff_fan_state:
        friendly_name: Fan State
        entity_id: device_tracker.sonff_fan
        value_template: >-
          {% if is_state('device_tracker.sonff_fan', 'home') %}
            100
          {% elif is_state('device_tracker.sonff_fan', 'not_home') %}
            0
          {% endif %}          


      sonoff_bedroom_parents_state:
        friendly_name: Parents Light
        entity_id: device_tracker.sonoff_bedroom_parents
        value_template: >-
          {% if is_state('device_tracker.sonoff_bedroom_parents', 'home') %}
            100
          {% elif is_state('device_tracker.sonoff_bedroom_parents', 'not_home') %}
            0
          {% endif %}
          

      sonoff_stairs_light_state:
        friendly_name: Stairs Light
        entity_id: device_tracker.sonoff_stairs_light
        value_template: >-
          {% if is_state('device_tracker.sonoff_stairs_light', 'home') %}
            100
          {% elif is_state('device_tracker.sonoff_stairs_light', 'not_home') %}
            0
          {% endif %}          
          

      sonoff_service_balcony_light_state:
        friendly_name: Service Balcony Light
        entity_id: device_tracker.sonoff_service_balcony_light
        value_template: >-
          {% if is_state('device_tracker.sonoff_service_balcony_light', 'home') %}
            100
          {% elif is_state('device_tracker.sonoff_service_balcony_light', 'not_home') %}
            0
          {% endif %}  

      sonoff_balcony_light_state:
        friendly_name: Service Balcony Light
        entity_id: device_tracker.sonoff_balcony_light
        value_template: >-
          {% if is_state('device_tracker.sonoff_balcony_light', 'home') %}
            100
          {% elif is_state('device_tracker.sonoff_balcony_light', 'not_home') %}
            0
          {% endif %}                      

          
      yeelinklightcolor1_miio86767262_state:
        friendly_name: Yeelink Light Color
        entity_id: device_tracker.yeelinklightcolor1_miio86767262
        value_template: >-
          {% if is_state('device_tracker.yeelinklightcolor1_miio86767262', 'home') %}
            100
          {% elif is_state('device_tracker.yeelinklightcolor1_miio86767262', 'not_home') %}
            0
          {% endif %}
          

      yeelink_light_strip1_miio98683770_state:
        friendly_name: Yeelight Strip
        entity_id: device_tracker.yeelink_light_strip1_miio98683770
        value_template: >-
          {% if is_state('device_tracker.yeelink_light_strip1_miio98683770', 'home') %}
            100
          {% elif is_state('device_tracker.yeelink_light_strip1_miio98683770', 'not_home') %}
            0
          {% endif %}

      esp_electric_state:
        friendly_name: Electric ESP
        entity_id: device_tracker.esp_electric
        value_template: >-
          {% if is_state('device_tracker.esp_electric', 'home') %}
            100
          {% elif is_state('device_tracker.esp_electric', 'not_home') %}
            0
          {% endif %}          


      unifi_access_point_state:
        friendly_name: Unifi Access Point
        entity_id: device_tracker.unifi_access_point
        value_template: >-
          {% if is_state('device_tracker.unifi_access_point', 'home') %}
            100
          {% elif is_state('device_tracker.unifi_access_point', 'not_home') %}
            0
          {% endif %}           

      tami4_power_state:
        friendly_name: Tami4 Power
        entity_id: device_tracker.tami4_power4
        value_template: >-
          {% if is_state('device_tracker.tami4_power', 'home') %}
            100
          {% elif is_state('device_tracker.tami4_power', 'not_home') %}
            0
          {% endif %}


      s20_xiaomi_state:
        friendly_name: Xiaomi on/off
        entity_id: device_tracker.s20_xiaomi
        value_template: >-
          {% if is_state('device_tracker.s20_xiaomi', 'home') %}
            100
          {% elif is_state('device_tracker.s20_xiaomi', 'not_home') %}
            0
          {% endif %}