title: Security
path: security
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: back_button
        variables:
          - title: Security
          - name: Camera's
          - button-name: Vacuum
          - icon: robot-vacuum
          - path: vacuum

        ### Center 6mp ### 
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.center_6mp
            title: Camera's  
            aspect_ratio: 16x9
          - !include ../decluttering_templates/blank-card.yaml

        ## Right Side Balcony ##
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.right_side_balcony
            title: Camera's
            aspect_ratio: 16x9
          - !include ../decluttering_templates/blank-card.yaml

        ## Entrance To The Building ##
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.entrance_to_the_building
            title: Camera's
            aspect_ratio: 16x9
          - !include ../decluttering_templates/blank-card.yaml 

        ## Xiaomi Dafang ###
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.xiaomi_dafang
            title: Camera's
            aspect_ratio: 16x9
          - !include ../decluttering_templates/blank-card.yaml

        ## Front Door ### 
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.front_door
            title: Camera's
            aspect_ratio: 16x9
          - !include ../decluttering_templates/blank-card.yaml          

  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '##### Doors'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.door_window_sensor_158d0001ef3425
              - name: Front Door
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.door_window_sensor_158d00027a59c6
              - name: Balcony Door
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.door_window_sensor_158d0002ea0754
              - name: Washing Machine
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - !include ../decluttering_templates/blank-card.yaml


      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.door_window_sensor_158d0002ea866a
              - name: AC Yakir door
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.door_window_sensor_158d0002ea9896
              - name: Laundry Dryer
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'

          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../decluttering_templates/blank-card.yaml


      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '##### Motion'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d0002047c5a
              - name: Shower
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d00024e7972
              - name: Laundry
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d000204bfcb
              - name: Parents
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - !include ../decluttering_templates/blank-card.yaml
          
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d000272bc63
              - name: Server Room
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info

          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d0002b42fa3
              - name: Guests Bbathroom
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info

          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../decluttering_templates/blank-card.yaml          

      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '##### Alarms'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: custom:decluttering-card
            template: switch_button_card
            variables:
              - entity: binary_sensor.smoke_sensor_158d00028ee7fb
              - name: Kitchen
              - icon: smoke-detector
              - show_last_changed: true
              - tap_action: more-info
          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - type: 'custom:button-card'
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../decluttering_templates/blank-card.yaml
      - type: 'custom:button-card'
        color_type: blank-card
        styles:
          card:
            - height: 10px