#################################################################
#                                                               #
#                    Packages/Alarm System                      #
#                                                               #
#################################################################

#################################################################
#   Group                                                       #
#################################################################

group:
  security:
    name: Security
    icon: mdi:security-home
    #view: yes
    entities:
      - group.alarms
      - group.motion      
      - group.doors
      
  alarms:
    name: Alarms
    icon: mdi:security
    #view: no
    entities:
      - binary_sensor.smoke_detector # חיישן עשן 
      
  motion:
    name: Motion
    icon: mdi:walk
    #view: no
    entities:
      - binary_sensor.main_shower_motion_sensor # חיישן מקלחת ראשית
      - binary_sensor.parents_shower_motion_sensor # חיישן תנועה מקלחת הורים
      - binary_sensor.guest_bathrom_motion_sensor # חיישן תנועה שירותי אורחים
      - binary_sensor.laundry_room_motion_sensor # חיישן תנועה חדר כביסה
      - binary_sensor.server_room_motion_sensor # חיישן תנועה חדר מחשבים
      
  doors:
    name: Doors
    icon: mdi:door
    #view: no
    entities:
      - binary_sensor.front_door_sensor # חיישן דלת כניסה
      - binary_sensor.balcony_door_sensor # חיישן מרפסת
      
      

    
#################################################################
#                                                               #
#                      Template Sensors                         #
#                                                               #
#################################################################

sensor:
  - platform: template
    sensors:
      door_count:
        value_template: >-
           {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | list | count | int }}


####################################################
#   Binary Sensor - Template                       #
####################################################
           
binary_sensor:
  - platform: template
    sensors:
      doors:
        friendly_name: Doors
        device_class: door
        entity_id: group.doors
        value_template: "{{ is_state('group.doors', 'on') }}"
        icon_template: >-
          {% if is_state('group.doors', 'on') %}
            mdi:door-open
          {% elif is_state('group.doors', 'off') %}
            mdi:door-closed         
          {% else %}
            mdi:alert
          {% endif %}
