#################################################################
#                                                               #
#                           sensors                             #
#                                                               #
#################################################################

sensor:
  - platform: template
    sensors:

      #################################################################
      #                           Motion sensor                       #
      #################################################################
    
      xiaomi_motion_shower_battery_parents:
        friendly_name: "Motion Showere Battery Parents"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.main_shower_motion_sensor.attributes.battery_level }}
          
      xiaomi_motion_laundry_room_battery:
        friendly_name: "Motion Laundry Room Battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.laundry_room_motion_sensor.attributes.battery_level }}          
          
      xiaomi_motion_sensor_computer_room_battery:
        friendly_name: "Motion Sensor Computer Room"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.server_room_motion_sensor.attributes.battery_level }}                    

      xiaomi_motion_sensor_guest_services_battery:
        friendly_name: "Motion Sensor Guest Services"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.guest_bathrom_motion_sensor.attributes.battery_level }}                              
          

      xiaomi_motion_sensor_shower_father_and_mother_battery:
        friendly_name: "Shower father and mother"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.parents_shower_motion_sensor.attributes.battery_level }}                              
                    

      #################################################################
      #                           Door Window Sensor                  #
      #################################################################          

      xiaomi_door_window_sensor_front_door_sensor:
        friendly_name: "Front Door Sensor"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.front_door_sensor.attributes.battery_level }}

      xiaomi_door_window_sensor_balcony_door_sensor:
        friendly_name: "Balcony Door Sensor"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.balcony_door_sensor.attributes.battery_level }}         

      xiaomi_door_window_sensor_washing_machine_sensor:
        friendly_name: "Washing Machine Sensor"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.washing_machine_sensor.attributes.battery_level }}                    

      xiaomi_door_window_sensor_laundry_dryer_sensor:
        friendly_name: "Laundry Dryer Sensor"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.laundry_dryer_sensor.attributes.battery_level }}                              


      #################################################################
      #                      Click Switch Sensor                      #
      #################################################################          

      xiaomi_sensor_switch_good_night_click:
        friendly_name: "Good night Click"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.switch_158d0001f36255.attributes.battery_level }}

      xiaomi_sensor_switch_lighting_balcony_click:
        friendly_name: "Lighting Balcony Click"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.switch_158d0001f3ddfd.attributes.battery_level }}          

      xiaomi_sensor_switch_lighting_service_balcony_click:
        friendly_name: "Lighting Service Balcony Click"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.switch_158d000224231e.attributes.battery_level }}          
          
      #################################################################
      #                           Smoke Sensor                        #
      #################################################################          

      xiaomi_smoke_sensor_kitchen_sensor:
        friendly_name: "Kitchen Smoke Sensor"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.binary_sensor.smoke_detector.attributes.battery_level }}          
