#################################################################
#                                                               #
#                      Packages/dogwalk                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Timer                                #
#                                                               #
#################################################################
timer:
  dogwalk:
    duration: '00:30:00'
    icon: mdi:paw
      

    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:

####################################################
#            Dog walk restart timer                #
####################################################

  - alias: 'Dog walk started'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: !secret binary_sensor_1
      to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.dogwalk
      - service: timer.start
        entity_id: timer.dogwalk                