#################################################################
#                                                               #
#                           sensors                             #
#                                                               #
#################################################################

sensor:

  - platform: template
    sensors:
  # WEATHER TEMPLATES
      current_temperature:
        friendly_name: Current Temperature
        value_template: >-
          {{ states('sensor.dark_sky_temperature') | round | int }}°
      current_feels:
        friendly_name: Current Feels Like
        value_template: >-
          feels like {{ states('sensor.dark_sky_apparent_temperature') | round | int }}°
      cloud_cover:
        friendly_name: Cloud Cover
        value_template: >-
          current cloud cover is {{ states('sensor.dark_sky_cloud_coverage') | round | int }}%
      nearest_storm:
        friendly_name: Nearest Storm
        value_template: >-
          nearest storm is {{ states('sensor.dark_sky_nearest_storm_distance') }} mi. away
      forecast_summary:
        friendly_name: Forecast
        value_template: >-
          {{ states('sensor.dark_sky_minutely_summary') }}
      current_humidity:
        friendly_name: Current Humidity
        value_template: >-
          {{ states('sensor.dark_sky_humidity') | round | int }}%
      daily_high:
        friendly_name: Today's High
        value_template: >-
          {{ states('sensor.dark_sky_daytime_high_temperature_0d') | round | int }}°
      daily_low:
        friendly_name: Today's Low
        value_template: >-
          {{ states('sensor.dark_sky_overnight_low_apparent_temperature_2d') | round | int }}°
      precipitation:
        friendly_name: Precipitation Detected
        value_template: >-
          {{ states('sensor.dark_sky_precip') | regex_replace(find='unknown', replace='none', ignorecase=true) }} detected
      precipitation_amount:
        friendly_name: Precipitation Amount
        value_template: >-
          {{ states('sensor.dark_sky_precip_intensity') | round(2, 'ceil') }} in. per hour
      precipitation_prob:
        friendly_name: Precipitation Probability
        value_template: >-
          probability: {{ states('sensor.dark_sky_precip_probability') | round | int }}%
      sunrise_today:
        friendly_name: "Sunrise Today"
        value_template: "{% set state = states('sensor.dark_sky_sunrise_0d') %}
                         {{ strptime(state, '%Y-%m-%d %H:%M:%S')
                         .replace(tzinfo=utcnow().tzinfo).astimezone(now().tzinfo) .strftime('%H:%M') }}"
      sunrise_tomorrow:
        friendly_name: "Sunrise Tomorrow"
        value_template: "{% set state = states('sensor.dark_sky_sunrise_1d') %}
                         {{ strptime(state, '%Y-%m-%d %H:%M:%S')
                         .replace(tzinfo=utcnow().tzinfo).astimezone(now().tzinfo) .strftime('%H:%M') }}"
      sunset_today:
        friendly_name: "Sunset Today"
        value_template: "{% set state = states('sensor.dark_sky_sunset_0d') %}
                         {{ strptime(state, '%Y-%m-%d %H:%M:%S')
                         .replace(tzinfo=utcnow().tzinfo).astimezone(now().tzinfo) .strftime('%H:%M') }}"
      sunset_tomorrow:
        friendly_name: "Sunset Tomorrow"
        value_template: "{% set state = states('sensor.dark_sky_sunset_1d') %}
                         {{ strptime(state, '%Y-%m-%d %H:%M:%S')
                         .replace(tzinfo=utcnow().tzinfo).astimezone(now().tzinfo) .strftime('%H:%M') }}"


    # TIME AND DATE TEMPLATES
      today_text:
        entity_id: sensor.date
        friendly_name: "Today is"
        value_template: "{{ now().strftime('%A / %B %d') }}"
      today_clock:
        entity_id: sensor.time
        friendly_name: "Today is"
        value_template: "{{ now().strftime('%A / %B %d / %H:%M') }}"
      clock:
        entity_id: sensor.time
        friendly_name: "Time is"
        value_template: "{{ now().strftime('%H:%M') }}"

   # THERMOSTAT TEMPLATES
      main_status:
        friendly_name: Main Floor Status
        value_template: >-
          {{ state_attr('climate.living_room', 'current_temperature') | round | int }}° / {{ state_attr('climate.living_room', 'current_humidity') | round | int }}% לחות
      upstairs_status:
        friendly_name: Upstairs Status
        value_template: >-
          {{ states('sensor.second_floor_temperature') | round | int }}° / {{ states('sensor.humidity_second_floor') | round | int }}% לחות



   # PRESENCE TRACKING TEMPLATES
      avi_location:
        value_template: "אבי {{ states('device_tracker.life360_avi_abeksis') | regex_replace(find='not_home', replace='לא נמצא', ignorecase=true) }}"
      nurit_location_2:
        value_template: "נורית {{ states('device_tracker.life360_nurit') | regex_replace(find='not_home', replace='לא נמצאת', ignorecase=true) }}"
      rotam_location:
        value_template: "רותם {{ states('device_tracker.rotam_iphone') | regex_replace(find='not_home', replace='לא נמצאת', ignorecase=true) }}"
      yakir_location:
        value_template: "יקיר {{ states('device_tracker.life360_yakir') | regex_replace(find='not_home', replace='לא נמצא', ignorecase=true) }}"
      liran_location:
        value_template: "לירן {{ states('device_tracker.life360_liran') | regex_replace(find='not_home', replace='לא נמצא', ignorecase=true) }}"        
          
  # TEXT TEMPLATES    
      text_mainfloor:
        value_template: "קומה ראשונה"
      text_secondfloor:
        value_template: "קומה שניה"
      text_parents:
        value_template: "הורים"
      text_pc_room:
        value_template: "מחשבים"
      text_stairs:
        value_template: "מדרגות"
      text_guests_bathroom:
        value_template: "מקלחת-שירותים"
      text_laundry:
        value_template: "חדר כביסה"
      text_balcony:
        value_template: "מרפסות"
      text_bathroom:
        value_template: "שירותים"
      text_miklahat:
        value_template: "מקלחת" 
      text_liran:
        value_template: "לירן"                  
      text_smoking:
        value_template: "עישון"
      text_hang:
        value_template: "כביסה" 
      text_air_conditioner:
        value_template: "מזגן מרכזי"         
      text_prozdor:
        value_template: "פרוזדור"
      text_kitchen:
        value_template: "מטבח"        
      text_good_night:
        value_template: "לילה טוב"
      text_living_room:
        value_template: "סלון"
      text_seating_area:
        value_template: "פינת ישיבה"        
