#################################################################
#                                                               #
#                Packages/PC Yakir Power Calculation            #
#                                                               #
#################################################################


#################################################################
#   Sensors                                                     #
################################################################# 
sensor:
  - platform: mqtt
    name: "Power Server Energy Today"
    state_topic: "tele/power_server_room/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Power Server Yesterday"
    state_topic: "tele/power_server_room/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Power Server Total"
    state_topic: "tele/power_server_room/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Power Server Power"
    state_topic: "tele/power_server_room/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"    
  - platform: mqtt
    name: "Power Server Total Cost"
    state_topic: "tele/power_server_room/SENSOR"
    value_template: '{{ (value_json["ENERGY"]["Total"] * 0.5487) | round(3) }}'
    unit_of_measurement: "₪"



#################################################################
#   Swithcs                                                     #
#################################################################
switch:
  - platform: mqtt
    name: "Power Server Room"
    state_topic: "stat/power_server_room/POWER"
    command_topic: "cmnd/power_server_room/POWER"
    availability_topic: "tele/power_server_room/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true 