#################################################################
#                                                               #
#                    Packages/Yeelight                          #
#                                                               #
#################################################################

      
#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################

group:
  yeelight:
    name: Yeelight
    view: no
    entities:
      - light.kitchen_strip_lamp
      - light.computer_room
      - light.yeelight_poop



light:
  - platform: mqtt  
    name: "Guests Bathroom Switch"
    command_topic: "cmnd/Guests_Bathroom_Switch/POWER"
    state_topic: "stat/Guests_Bathroom_Switch/POWER"
    availability_topic: "tele/Guests_Bathroom_Switch/LWT"   
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"  
    retain: true      
    
#################################################################
#                                                               #
#                           lights                              #
#                                                               #
#################################################################

yeelight:
    devices:
      192.168.1.153:
        name: Yeelight Poop
        transition: 1000
  
      192.168.1.196:
        name: computer room
        transition: 1000
              
      192.168.1.171:
        name: Kitchen strip Lamp
        transition: 1000 

      192.168.1.208:
        name: Laundry Room lighting
        transition: 1000         
    
    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:

#################################################################
#                        חיישן תנועה שירותי אורחים                     #
#################################################################

#########                                                  ######
#########  Code Moved To Node-Red Under Flow Motion-Sensor ######
#########                                                  ######

  # - alias: Turn on lights poop based on montion
  #   initial_state: 'on'  
  #   trigger:
  #   - entity_id: binary_sensor.motion_sensor_158d0002b42fa3 
  #     platform: state
  #     to: 'on'
  #   action:
  #   - service: light.turn_on
  #     entity_id: light.yeelight_poop
  #     data:
  #       brightness_pct: 100
  #       kelvin: 5000    

  # - alias: Turn off lights poop based on montion
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: binary_sensor.motion_sensor_158d0002b42fa3
  #     to: 'off'
  #     for:
  #       seconds: 30
  #   action:
  #   - service: light.turn_off
  #     entity_id: light.yeelight_poop


#################################################################
#                       חיישן תנועה חדר כביסה                        #
#################################################################
 
  - alias: Turn on lights laundry based on montion
    initial_state: 'on'  
    trigger:
    - entity_id: binary_sensor.motion_sensor_158d00024e7972
      platform: state
      to: 'on'
    action:
    - service: light.turn_on
      entity_id: light.laundry_room_lighting
      data:
        brightness_pct: 100
        kelvin: 5500   

  - alias: Turn off lights laundry based on montion
    initial_state: 'on'  
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00024e7972
      to: 'off'
      for:
        seconds: 30
    action:
    - service: light.turn_off
      entity_id: light.laundry_room_lighting      

#################################################################
#                      חיישן תנועה חדר מחשבים                       #
#################################################################

  - alias: Turn on lights pc room based on montion
    initial_state: 'on'  
    trigger:
    - entity_id: binary_sensor.motion_sensor_158d000272bc63
      platform: state
      to: 'on'
    action:
    - service: light.turn_on
      entity_id: light.computer_room
      data:
        brightness_pct: 100
        kelvin: 6000        

  - alias: Turn off lights pc room based on montion
    initial_state: 'on'  
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d000272bc63
      to: 'off'
      for:
        seconds: 30
    action:
    - service: light.turn_off
      entity_id: light.computer_room