#################################################################
#                                                               #
#                          Email Content                        #
#                                                               #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################
homeassistant:
  customize:
    sensor.abeksis_gmail_com:
      friendly_name: Gmail Avi
      icon: mdi:email-outline
      assumed_state: false 

#################################################################
#                                                               #
#                          sensor                               #
#                                                               #
#################################################################

sensor:

  - platform: imap
    server: imap.gmail.com
    username: !secret avi_gmail_username
    password: !secret avi_gmail_password
    port: 993      
    
  - platform: imap
    server: imap.gmail.com
    username: !secret nurit_gmail_username
    password: !secret nurit_gmail_password
    port: 993     