#################################################################
#                                                               #
#                          Email Content                        #
#                                                               #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################
homeassistant:
  customize:
    sensor.abeksis_gmail_com:
      friendly_name: avi-mail
      icon: mdi:email-outline
      assumed_state: false

#################################################################
#                                                               #
#                          sensor                               #
#                                                               #
#################################################################

sensor:
  - platform: imap
    server: imap.gmail.com
    port: 993    
    username: !secret avi_gmail_username
    password: !secret avi_gmail_password
    
  - platform: imap
    server: imap.gmail.com
    port: 993    
    username: !secret nurit_gmail_username
    password: !secret nurit_gmail_password