######################################################################
### MANUAL ALARM PANEL                                             ###
######################################################################

# ALARM FOR AWAY
- alias: Alarm Away
  initial_state: 'true'
  hide_entity: True
  trigger:
  - entity_id: !secret binary_sensor_1
    platform: state
    to: 'on'
  - entity_id: !secret binary_sensor_2 # חיישן דלת מרפסת
    platform: state
    to: 'on'
  - entity_id: !secret binary_sensor_3 # חיישן עשן
    platform: state
    to: 'on'
  - entity_id: !secret binary_sensor_4 # חיישן תנועה שירותי אורחים
    platform: state
    to: 'on'
  condition:
  - entity_id: alarm_control_panel.home_alarm
    state: 'armed_away'
    condition: state
  action:
  - data:
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_trigger

# ALARM FOR AT HOME
- alias: Alarm Home
  initial_state: 'true'
  hide_entity: True
  trigger:
  - entity_id: !secret binary_sensor_1 # חיישן דלת כניסה
    platform: state
    to: 'on'
  - entity_id: !secret binary_sensor_2 # חיישן דלת מרפסת
    platform: state
    to: 'on'
  - entity_id: !secret binary_sensor_3 # חיישן עשן
    platform: state
    to: 'on'
  condition:
  - entity_id: alarm_control_panel.home_alarm
    state: 'armed_home'
    condition: state
  action:
  - data:
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_trigger

# ALARM FOR AT NIGHT
- alias: Alarm Night
  initial_state: 'true'
  hide_entity: True
  trigger:
  - entity_id: !secret binary_sensor_1 # חיישן דלת כניסה
    platform: state
    to: 'on'
  condition:
  - entity_id: alarm_control_panel.home_alarm
    state: 'armed_night'
    condition: state
  action:
  - data:
      entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_trigger

################################################################
### ALARM TRIGGERS                                             #
################################################################

- alias: Triggered Flash
  initial_state: 'true'
  hide_entity: True
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: 'triggered'
  action:
  - data:
      entity_id: script.light_flash
    service: script.turn_on
  - data:
      entity_id: script.xiaomi_alarm_siren
    service: script.turn_on

################################################################
### ALARM DISARMED                                             #
################################################################

- alias: Disarmed Off
  initial_state: 'true'
  hide_entity: True
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
    to: 'disarmed'
  action:
  - data:
      entity_id: script.light_flash
    service: script.turn_off
  - data:
      entity_id: script.xiaomi_alarm_siren
    service: script.turn_off
  - data:
      entity_id: script.xiaomi_alarm_siren_loop
    service: script.turn_off
  - data:
      entity_id: script.all_lights_turn_on
    service: script.turn_on

- alias: Alarm Alert
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'triggered'
  action:
  - service: notify.avi_telegram
    data:
      title: "Home Alarm"
      message: "ALARM ALARM! The alarm has sounded! ALARM ALARM"
      

- alias: Alarm Away Notification
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
  action:
  - service: notify.avi_telegram
    data:
      title: "Home Alarm"
      message: "The Alarm is enabled for Away!"

- alias: Alarm Home Notification
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_home'
  action:
  - service: notify.avi_telegram
    data:
      title: "Home Alarm"
      message: "The Alarm is on for Home!"


- alias: Alarm Night Notification
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_night'
  action:
  - service: notify.avi_telegram
    data:
      title: "Home Alarm"
      message: "The Alarm is switched on for the Night!"


- alias: Alarm Disarm Notification
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'disarmed'
  action:
  - service: notify.avi_telegram
    data:
      title: "Home Alarm"
      message: "The Alarm is switched off!"  


# Alarm Notifications/Automatic Disarm
- alias: Alarm Disarm Avi Away
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: person.avi
    to: 'home'
    for:
      seconds: 30
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm 
      state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_disarm
      data: !secret alarmcode   

- alias: Alarm Disarm Avi Home
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: person.avi
    to: 'home'
    for:
      seconds: 30
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm  
      state: 'armed_home'
  action:
    - service: alarm_control_panel.alarm_disarm
      data: !secret alarmcode  

- alias: Alarm Disarm Nurit Away
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: person.nurit
    to: 'home'
    for:
      seconds: 30
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm  
      state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_disarm
      data: !secret alarmcode  

- alias: Alarm Disarm Nurit Home
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: person.nurit
    to: 'home'
    for:
      seconds: 30
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm  
      state: 'armed_home'
  action:
    - service: alarm_control_panel.alarm_disarm
      data: !secret alarmcode  

- alias: Alarm Activation Alert
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: group.device_status_3
    from: 'home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm  
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.home_alarm  
        state: 'armed_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      data: !secret alarmcode  

#simple alarm automations
- alias: simple alarm activate
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: input_boolean.simple_alarm
    to: 'on'
  action:
    - service: alarm_control_panel.alarm_arm_home
      data: !secret alarmcode 
- alias: simple alarm deactivate
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: input_boolean.simple_alarm
    to: 'off'
  action:
    - service: alarm_control_panel.alarm_disarm
      data: !secret alarmcode 

