# DOORS OPEN WILL SEND ALERTS TO Mobile
- alias: Front Door Open
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: sensor.living_room_temp
    to: 'on'
  - platform: state
    entity_id: sensor.living_room_temp
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.avi
        state: 'not_home'
      - condition: state
        entity_id: person.nurit
        state: 'not_home'  
  action:
  - service_template: >
        {% if (is_state('person.avi', 'not_home')) and (is_state('person.nurit', 'not_home'))  %}
          notify.avi_telegram
        {% elif (is_state('person.avi', 'home')) and (is_state('person.nurit', 'not_home')) %}
          notify.avi_telegram
        {% elif (is_state('person.avi', 'not_home')) and (is_state('person.nurit', 'home')) %}
          notify.nurit_telegram
        {% elif (is_state('person.avi', 'home')) and (is_state('person.nurit', 'home')) %}
          notify.nurit_telegram        
        {% endif %}
    data_template:
      title: "בית חכם"
      message: >
        {% if is_state('binary_sensor.front_door_sensor', 'on') %}
          דלת הכניסה נפתחה!
        {% elif is_state('binary_sensor.front_door_sensor', 'off') %}
          דלת הכניסה נסגרה!
        {% endif %}



# Front Door Snapshot
- alias: 'Front Door Snapshot'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.living_room_temp
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'device_tracker.avi_avi'
        state: 'not_home'
      - condition: state
        entity_id: 'device_tracker.nurit_iphone' # מכוון לספק מידע דרך הראוטר - אמין יותר בשביל 
        state: 'not_home'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_door
        filename: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"

    - service: notify.avi_telegram
      data:
        title: "בית חכם"
        message: "מישהו לא מורשה פתח את הדלת"
        data:
          photo:
            - file: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
              capture: Front House Camera              

    - service: notify.nurit_telegram
      data:
        title: "בית חכם"
        message: "מישהו לא מורשה פתח את הדלת"
        data:
          photo:
            - file: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
              capture: Front House Camera   


# THE DOOR OPEN FOR MORE 1 MIN
- alias:  notify if the home door was open for more then 1 min
  initial_state: 'on'  
  trigger:
    platform: state
    entity_id: sensor.living_room_temp
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
  - service: notify.avi_telegram
    data:
      title: "בית חכם"
      message: 'דלת הבית פתוחה יותר מדקה'
          
  - service: notify.nurit_telegram
    data:
      title: "בית חכם"
      message: 'דלת הבית פתוחה יותר מדקה'          