## Home Assistant is Up and Running ##

- alias: 'Startup Notification'
  initial_state: 'on'  
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.avi_telegram 
      data:
        title: 'System info'
        message: 'Home Assistant is Up and Running'

    - service: mqtt.publish 
      data:
        topic: "cmnd/sonoffs/power" # Update the power state of all the sonoffs
        payload: "check"    
        
    - service: mqtt.publish 
      data:
        topic: "cmnd/sonoffs/power1"
        payload: "check"      
        
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power2"
        payload: "check"

    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power3"
        payload: "check"

    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power4"
        payload: "check"


#########################  boiler  ##########################        

  ## Switched to control via NODE RED ##

  # - alias: notify if the boiler is on
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: switcher_aio.control_device_switch
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "חמור מאוד, אבי"
  #       message: 'מישהו הדליק את הדוד' 
        


  #########################  Light  ##########################   
  
  ##  Switched to control via NODE RED ##

  # - alias:  notify if the balcony in ON
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state 
  #     entity_id: light.balcony
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "האור דולק במרפסת" 

 
  ##  Canceled #

  # - alias:  notify if the Service balcony in ON
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.service_balcony
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "האור דולק במרפסת"

  ##  Canceled #

  # - alias:  notify if the laundry room ON
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.laundry_room_lighting
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "האור דולק בחדר כביסה"

  ##  Canceled #

  # - alias:  notify if the light in room off liran in ON
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.liran_room
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "האור דולק בחדר של לירן" 


  ## Switched to control via NODE RED ##

  # - alias:  notify if the guests bathroom ON
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.guests_bathroom_switch
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "התאורה דולקת בשירותי אורחים"

  ##  Canceled ##
  
  # - alias:  notify if the prozdor bathroom ON
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.prozdor
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "התאורה דולקת בפרוזדור"

  
  ##  Canceled #
  
  # - alias: notify if the miklahat is on
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.miklahat
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "התאורה דולקת במקלחת"


  ## Switched to control via NODE RED ##

  # - alias:  notify if the stairs is on
  #   initial_state: 'on'  
  #   trigger:
  #     platform: state
  #     entity_id: light.stairs
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     service: notify.avi_telegram
  #     data:
  #       title: "שלום אבי"
  #       message: "התאורה דולקת במדרגות"        