###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 169
  packages: !include_dir_named packages
  customize: !include config/customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.1
    - type: homeassistant

  whitelist_external_dirs:
    - /config
    - /config/tmp
    - /config/backup/hass


###################################################
#                                                 #
#                     lovelace                    #
#                                                 #
###################################################
lovelace:
  mode: yaml



####################################################
#                                                  #
#                     iFrame                       #
#                                                  #
####################################################

panel_iframe:
  node_red:
   title: Node Red
   icon: mdi:file-plus
   url: !secret node_red

  unraid:
   title: Unraid
   icon: mdi:desktop-tower
   url: !secret unraid
   
  cloud9: 
   title: ide
   icon: mdi:cloud-upload-outline
   url: !secret cloud9  
   
  tasmoadmin: 
   title: TasmoAdmin
   icon: mdi:omega
   url: !secret tasmoadmin

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

config:

system_health:

http:
  # api_password: !secret http_password
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
  - 127.0.0.1 #localhost
  - 192.168.1.1 #router
  - 172.18.0.2 #letsencryot 
  - 172.17.0.3 #mariadb


updater:
discovery:
conversation:
speedtestdotnet:
history:
logbook:
mobile_app:
hacs:
  token: !secret my_github_access_token
map:
sun:
  show_installable: false
  hide_sensor: true
  track:
    - components
    - cards
    - python_scripts
  card_urls:
      - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
      - https://raw.githubusercontent.com/ljmerza/waze-card/master/updater.json
      - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
      - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
      
tts:
  - platform: google_translate
    service_name: google_say


####################################################
#                                                  #
#                 Customizations                   #
#                                                  #
####################################################

#customizer:
#  custom_ui: local


frontend:
  themes: !include configuration/themes.yaml #For Samsung Notte design
  javascript_version: auto
  extra_html_url:
    - /local/custom_ui/fontawesome/hass-fontawesome-solid.html
    - /local/custom_ui/fontawesome/hass-fontawesome-regular.html
    - /local/custom_ui/fontawesome/hass-fontawesome-brands.html  
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

####################################################
#                                                  #
#                 Logger - קובץ לוג                 #
#                                                  #
####################################################

logger:
  default: warn
    

####################################################
#                                                  #
#                      Cloud                       #
#                                                  #
####################################################

cloud: !include config/cloud.yaml

# ####################################################
# #                                                  #
# #                      owntracks                   #
# #                                                  #
# ####################################################

# owntracks:

####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################

mqtt: 
  password: !secret http_password
  broker:  !secret broker_host
  username: !secret http_username
  client_id: HOME_ASSISTANT

####################################################
#                                                  #
#                      xiaomi                      #
#                                                  #
####################################################
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi


####################################################
#                                                  #
#                      google                      #
#                                                  #
####################################################

google:
  client_id: !secret client_id
  client_secret: !secret client_secret 


####################################################
#                                                  #
#                    Telegram Bot                  #
#                                                  #
#################################################### 

telegram_bot:
  - platform: polling
    api_key: !secret TelegramBotApiKey
    allowed_chat_ids:
      - !secret TelegramChatIDNum1   



## Weather Dark Sky
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api

####################################################
#                                                  #
#                    Switcher V2                   #
#                                                  #
####################################################       

switcher_aio:
  phone_id: !secret switcher_phone_id
  device_id: !secret switcher_device_id
  device_password: !secret switcher_device_password 

 

####################################################
#                                                  #
#                    Birthday Sensor               #
#                                                  #
####################################################

python_script: 
  
####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

#automation: !include_dir_merge_list config/automation/
#group: !include config/groups.yaml
media_player: !include config/media_players.yaml
shell_command: !include config/shell_command.yaml
sensor: !include config/sensors.yaml
notify: !include config/notify.yaml
switch: !include config/switchs.yaml
weblink: !include config/weblink.yaml
cloudflare: !include config/cloudflare.yaml
zone: !include config/zones.yaml
timer: !include config/timer.yaml
input_datetime: !include config/input_datetime.yaml
input_boolean: !include configuration/input_boolean.yaml #For Samsung Notte design / עיצוב סמסונג 
automation: !include configuration/automations.yaml #For Samsung Notte design / עיצוב סמס
input_select: !include configuration/input_select.yaml #For Samsung Notte design / עיצוב סמס




# camera:
#   name: Paulus
#   platform: generic
#   still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ state_attr('ituran.skodakodiak', 'lat') }},{{ state_attr('ituran.skodakodiak', 'lon') }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ state_attr('ituran.skodakodiak', 'lat') }},{{ state_attr('ituran.skodakodiak', 'lon') }}&key=AIzaSyAs1SYji-6uXmQTbm0qSLHxPGarAwpbCTA
#   limit_refetch_to_url_change: true