homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 169
  packages: !include_dir_named packages/
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: homeassistant
    
####################################################
#                     Enables                      #
####################################################

http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
  - 127.0.0.1
  - !secret home_router
  - !secret letsencrypt_container
  - !secret database_server
  - !secret docker_something_or_othe    

frontend:
  themes: !include_dir_merge_named themes/


########################################################
# Speedtest.net                                        #
########################################################
speedtestdotnet:

########################################################
# Browser-mod makes the browser more useful + required #
########################################################
browser_mod:

########################################################
# Home Assistant Mobile App Support                    #
########################################################
mobile_app:

#######################################################
# improve the lovelace yaml parser for Home Assistant #
#######################################################
lovelace_gen:

#####################################
#              Required             #
#####################################
lovelace:
  mode: yaml

#####################################################
#              Required by home assistant           #
#####################################################
default_config:


#####################################################
#              Required by home assistant           #
#####################################################
discovery:

####################################################
#                      Weather Dark Sky            #
####################################################
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api


####################################################
#                      xiaomi                      #
####################################################
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi

####################################################
#                Google  Calendar                  #
####################################################
google:
  client_id: !secret client_id
  client_secret: !secret client_secret 


####################################################
#                    Telegram Bot                  #
#################################################### 
telegram_bot:
  - platform: polling
    api_key: !secret TelegramBotApiKey
    allowed_chat_ids:
      - !secret telgram_avi   
      - !secret telgram_nurit  


####################################################
#                      MQTT                        #
####################################################
mqtt: 
  password: !secret http_password
  broker:  !secret broker_host
  username: !secret http_username  

####################################################
#                      Hacs                        #
####################################################
hacs:
  token: !secret my_github_access_token  


####################################################
#                      include                     #
####################################################
automation: !include_dir_merge_list configuration/automations/ #place every automation in this folder
notify: !include configuration/notify/notify.yaml # by home assistent
alarm_control_panel: !include configuration/alarm_control_panel/alarms.yaml # Alarm Panel
webostv: !include configuration/webostv/webostv.yaml # LG TV
group: !include configuration/group/group.yaml # jimz011/homekit
cloud: !include configuration/cloud/cloud.yaml # amazon alexa
zone: !include configuration/zone/zone.yaml # place every zone in this folder
switch: !include configuration/switch/switch.yaml # for tami 4 and mor
sensor: !include_dir_merge_list configuration/sensor/ #place every sensor in this folder