#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################


# life360 #
life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  # MPH, assuming imperial units.
  # If using metric (KPH), the equivalent would be 29.
  driving_speed: 29
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  # Set comm error thresholds so first is not logged,
  # second is logged as a WARNING, and third and fourth
  # are logged as ERRORs.
  warning_threshold: 2
  error_threshold: 3


#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    device_tracker.avi_avi:
      friendly_name: Avi 
      entity_picture: /local/known_devices/avi.png
      
    sensor.next_bus:
      icon: 'mdi:bus-clock'      
 
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
################################################################# 
      
group:
  people at home:
    name: People
    view: no
    entities:
      - device_tracker.avi_avi
      - sensor.avi_battery


    
#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:

  # life360 #
  - platform: template
    sensors:
      life360_avi_battery:
        friendly_name: "Avi battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_avi_abeksis.attributes.battery }}


      life360_nurit_battery:
        friendly_name: "Nurit battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_nurit.attributes.battery }}
          
      life360_yakir_battery:
        friendly_name: "Yakir battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_yakir.attributes.battery }}

      life360_liran_battery:
        friendly_name: "Liran battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_liran.attributes.battery }}          

  - platform: template
    sensors:
      next_bus:
        friendly_name: Time to Next Bus
        unit_of_measurement: min
        value_template: >
          {% set min_now = states('sensor.time').split(':')[1]|int %}
          {% set time_now_h = states('sensor.time').split(":",)[0].replace("0", "")|int %}
          {% set time_now_m = states('sensor.time').split(":",)[1].replace("0", "")|int %}
          {% if now().strftime("%H")|int < 5 %}
            {{ (330 - (time_now_h*60) + (time_now_m)) }}
          {% elif now().strftime("%H")|int < 6 %}
            {{ 29 - min_now if min_now < 29 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 7 %}
            {{ 19 - min_now if min_now < 19 else 39 - min_now if min_now < 39 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 8 %}
            {{ 14 - min_now if min_now < 14 else 29 - min_now if min_now < 29 else 44 - min_now if min_now < 44 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 9 %}
            {{ 14 - min_now if min_now < 9 else 29 - min_now if min_now < 29 else 49 - min_now if min_now < 49 }}
          {% elif now().strftime("%H")|int < 15 %}
            {{ 9 - min_now if min_now < 9 else 29 - min_now if min_now < 29 else 49 - min_now if min_now < 49 }}
          {% elif now().strftime("%H")|int < 18 %}
            {{ 14 - min_now if min_now < 14 else 24 - min_now if min_now < 24 else 39 - min_now if min_now < 39 else 54 - min_now if min_now < 54 }}
          {% elif now().strftime("%H")|int < 20 %}
            {{ 14 - min_now if min_now < 9 else 34 - min_now if min_now < 34 else 59 - min_now if min_now < 59 }}
          {% elif now().strftime("%H")|int < 24 %}
            {{ 29 - min_now if min_now < 29 else 59 - min_now if min_now < 59 }}
          {% else %}
            Unknown
          {% endif %} 