#################################################################
#                                                               #
#                     Packages/IOT Windows-Monitor              #
#                                                               #
#################################################################
  


#################################################################
#                                                               #
#                          Binary Sensor                        #
#                                                               #
################################################################# 

binary_sensor:


#################################################################
#                          WinDows 10 Vm                        #
#################################################################


  - platform: mqtt
    name: "WinDows 10 Vm - Connected"
    state_topic: "iotlink/workgroup/windows_10_vm/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1


#################################################################
#                          Windows Yakir                        #
#################################################################


  - platform: mqtt
    name: "Windows 10 Yakir - Connected"
    state_topic: "iotlink/workgroup/yakir/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1


#################################################################
#                          Windows Liran                        #
#################################################################


  - platform: mqtt
    name: "Windows liran  - Connected"
    state_topic: "iotlink/workgroup/liran/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1




#################################################################
#                                                               #
#                          camera                               #
#                                                               #
################################################################# 

camera:

#################################################################
#                          Windows 10 Vm                        #
#################################################################

  - platform: mqtt
    name: "Windows 10 Vm - Screen 0"
    topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/display/0/screen"

#################################################################
#                          Windows 10 liran                     #
#################################################################

  - platform: mqtt
    name: "Windows 10 liran - Screen 0"
    topic: "iotlink/workgroup/liran/windows-monitor/stats/display/0/screen"


#################################################################
#                          Windows 10 yakir                     #
#################################################################

  - platform: mqtt
    name: "Windows 10 yakir - Screen 0"
    topic: "iotlink/workgroup/yakir/windows-monitor/stats/display/0/screen"

#################################################################
#                                                               #
#                          sensor                               #
#                                                               #
################################################################# 

sensor:

  - platform: mqtt
    name: "Windows 10 Vm - CPU Usage"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/cpu"
    unit_of_measurement: '%'
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Vm - RAM Usage"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/memory/usage"
    unit_of_measurement: '%'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Vm - RAM Available"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/memory/available"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Vm - RAM Used"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/memory/used"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Vm - HDD Total Free Space (C)"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/hard-drive/c/total-free-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    # value_template: "{{ ((value | int / 1024) | round(0)) }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Vm - HDD Used Space (C)"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/hard-drive/c/used-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    # value_template: "{{ ((value | int / 1024 / 1024 / 1024) | round(0)) }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Vm - Current User"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/current-user"
    unit_of_measurement: ''
    icon: mdi:account
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 VM - Network IPv4"
    state_topic: "iotlink/workgroup/windows_10_vm/windows-monitor/stats/network/0/ipv4"
    unit_of_measurement: ''
    icon: mdi:lan
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/windows_10_vm/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1


#################################################################
#                          Windows Yakir                        #
#################################################################

  - platform: mqtt
    name: "Windows 10 Yakir - CPU Usage"
    state_topic: "iotlink/workgroup/yakir/windows-monitor/stats/cpu"
    unit_of_measurement: '%'
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/yakir/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Yakir - RAM Usage"
    state_topic: "iotlink/workgroup/yakir/windows-monitor/stats/memory/usage"
    unit_of_measurement: '%'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/yakir/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Yakir - RAM Available"
    state_topic: "iotlink/workgroup/yakir/windows-monitor/stats/memory/available"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/yakir/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Yakir - RAM Used"
    state_topic: "iotlink/workgroup/yakir/windows-monitor/stats/memory/used"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/yakir/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1


  - platform: mqtt
    name: "Windows 10 Yakir - HDD Total Free Space (C)"
    state_topic: "iotlink/workgroup/yakir/windows-monitor/stats/hard-drive/c/total-free-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/yakir/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows 10 Yakir - HDD Used Space (C)"
    state_topic: "iotlink/workgroup/yakir/windows-monitor/stats/hard-drive/c/used-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ ((value | int / 1024 / 1024 / 1024) | round(0)) }}"
    availability_topic: "iotlink/workgroup/yakir/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

#################################################################
#                          Windows Liran                        #
#################################################################

  - platform: mqtt
    name: "Windows Liran - CPU Usage"
    state_topic: "iotlink/workgroup/liran/windows-monitor/stats/cpu"
    unit_of_measurement: '%'
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/liran/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows Liran - RAM Usage"
    state_topic: "iotlink/workgroup/liran/windows-monitor/stats/memory/usage"
    unit_of_measurement: '%'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/liran/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows Liran - RAM Available"
    state_topic: "iotlink/workgroup/liran/windows-monitor/stats/memory/available"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/liran/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows Liran - RAM Used"
    state_topic: "iotlink/workgroup/liran/windows-monitor/stats/memory/used"
    unit_of_measurement: 'MB'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/liran/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1


  - platform: mqtt
    name: "Windows Liran - HDD Total Free Space (C)"
    state_topic: "iotlink/workgroup/liran/windows-monitor/stats/hard-drive/c/total-free-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/liran/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Windows Liran - HDD Used Space (C)"
    state_topic: "iotlink/workgroup/liran/windows-monitor/stats/hard-drive/c/used-space"
    unit_of_measurement: 'GB'
    icon: mdi:harddisk
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/liran/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

switch:
  - platform: template
    switches:
      my_computer:
        friendly_name: "Windows 10 VM"
        value_template: "{{ is_state('binary_sensor.my_computer_connected', 'on') }}"
        turn_on:
          service: script.my_computer_wake
        turn_off:
          service: script.my_computer_suspend
        icon_template: mdi:laptop


#################################################################
#                                                               #
#                          script                               #
#                                                               #
#################################################################

script:

  my_computer_wake_vm:
    alias: "Windows 10 VM - Wake"
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "!secret mac_lan"

  my_computer_shutdown_vm:
    alias: "Windows 10 VM - Shutdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/shutdown"
          payload: ""

  my_computer_suspend_vm:
    alias: "Windows 10 VM - Suspend"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/suspend"
          payload: ""

  my_computer_hibernate_vm:
    alias: "Windows 10 VM - Hibernate"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/hibernate"
          payload: ""

  my_computer_reboot_vm:
    alias: "WinDows 10 VM - Reboot"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/reboot"
          payload: ""

  my_computer_lock_vm:
    alias: "Windows 10 VM - Lock"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/lock"
          payload: ""

  my_computer_logoff_vm:
    alias: "Windows 10 VM - Logoff"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/logoff"
          payload: ""

  my_computer_vol_mute_vm:
    alias: "Windows 10 VM - Toggle Mute"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/volume/mute"
          payload: ""

  my_computer_vol_max_vm:
    alias: "Windows 10 VM - Vol Max"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/volume/set"
          payload: "100"

  my_computer_run_chrome_vm:
    alias: "Windows 10 VM - Run Chrome"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/windows_10_vm/commands/run"
          payload: '{ "command": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", "args": "https://www.google.co.il", "path": "C:\\Program Files (x86)\\Google\\Chrome\\Application", "user": "", "visible": true, "fallback": true }'

#################################################################
#                          Windows Yakir                        #
#################################################################

  my_computer_wake_yakir:
    alias: "Windows 10 Yakir - Wake"
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "!secret mac_lan_yakir"

  my_computer_shutdown_yakir:
    alias: "Windows 10 Yakir - Shutdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/shutdown"
          payload: ""

  my_computer_suspend_yakir:
    alias: "Windows 10 Yakir - Suspend"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/suspend"
          payload: ""

  my_computer_hibernate_yakir:
    alias: "Windows 10 Yakir - Hibernate"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/hibernate"
          payload: ""

  my_computer_reboot_yakir:
    alias: "Windows 10 Yakir - Reboot"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/reboot"
          payload: ""

  my_computer_lock_yakir:
    alias: "Windows 10 Yakir - Lock"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/lock"
          payload: ""

  my_computer_logoff_yakir:
    alias: "Windows 10 Yakir - Logoff"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/logoff"
          payload: ""

  my_computer_vol_mute_yakir:
    alias: "Windows 10 Yakir - Toggle Mute"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/volume/mute"
          payload: ""

  my_computer_vol_max_yakir:
    alias: "Windows 10 Yakir - Vol Max"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/volume/set"
          payload: "100"

  my_computer_run_chrome_yakir:
    alias: "Windows 10 Yakir - Run Chrome"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/yakir/commands/run"
          payload: '{ "command": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", "args": "https://www.google.co.il", "path": "C:\\Program Files (x86)\\Google\\Chrome\\Application", "user": "", "visible": true, "fallback": true }'

#################################################################
#                          Windows liran                        #
#################################################################

  my_computer_wake_liran:
    alias: "Windows Liran - Wake"
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "!secret mac_lan_liran"

  my_computer_shutdown_liran:
    alias: "Windows Liran - Shutdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/shutdown"
          payload: ""

  my_computer_suspend_liran:
    alias: "Windows Liran - Suspend"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/suspend"
          payload: ""

  my_computer_hibernate_liran:
    alias: "Windows Liran - Hibernate"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/hibernate"
          payload: ""

  my_computer_reboot_liran:
    alias: "Windows Liran - Reboot"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/reboot"
          payload: ""

  my_computer_lock_liran:
    alias: "Windows Liran - Lock"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/lock"
          payload: ""

  my_computer_logoff_liran:
    alias: "Windows Liran - Logoff"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/logoff"
          payload: ""

  my_computer_vol_mute_liran:
    alias: "Windows Liran - Toggle Mute"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/volume/mute"
          payload: ""

  my_computer_vol_max_liran:
    alias: "Windows Liran - Vol Max"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/volume/set"
          payload: "100"

  my_computer_run_chrome_liran:
    alias: "Windows Liran - Run Chrome"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/liran/commands/run"
          payload: '{ "command": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", "args": "https://www.google.co.il", "path": "C:\\Program Files (x86)\\Google\\Chrome\\Application", "user": "", "visible": true, "fallback": true }'
