#################################################################
#                                                               #
#                Packages/Television Power                      #
#                                                               #
#################################################################


#################################################################
#   Sensors                                                     #
################################################################# 
sensor:
  - platform: mqtt
    name: "Television Power Energy Today"
    state_topic: "tele/television_power/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Television Power Yesterday"
    state_topic: "tele/television_power/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Television Power Total"
    state_topic: "tele/television_power/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "Television Power Power"
    state_topic: "tele/television_power/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"    
  - platform: mqtt
    name: "Television Power Total Cost"
    state_topic: "tele/television_power/SENSOR"
    value_template: '{{ (value_json["ENERGY"]["Total"] * 0.5487) | round(3) }}'
    unit_of_measurement: "₪"



#################################################################
#   Swithcs                                                     #
#################################################################
switch:
  - platform: mqtt
    name: "Television Power"
    state_topic: "stat/television_power/POWER"
    command_topic: "cmnd/television_power/POWER"
    availability_topic: "tele/television_power/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true 