#################################################################
#                                                               #
#                    Packages/Birthday                          #  
#                                                               # 
#                                                               #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

#################################################################
# Build the excitement
#################################################################
  - alias: Wedding Anniversary Notification
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.anniversary_wedding_day
        to: '0'
    action:
      - delay:
          hours: 8
      - service: notify.avi_telegram
        data:
          title: "Wedding day"
          message: "We are today year married! Congrats!"


  # Birthday Notifications
  - alias: Nurit Birthday Notification
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.birthday_nurit
        to: '0'
    action:
      - delay:
          hours: 8
      - service: notify.avi_telegram
        data:
          title: "Birthday"
          message: "Nurit is Birthday Wish her a happy birthday"
 
 
  - alias: Avi Birthday Notification
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.birthday_avi
        to: '0'
    action:
      - delay:
          hours: 8
      - service: notify.avi_telegram
        data:
          title: "Birthday"
          message: "Nurit is Birthday Wish him a happy birthday"
 

  - alias: Rotem Birthday Notification
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.birthday_rotem
        to: '0'
    action:
      - delay:
          hours: 8
      - service: notify.avi_telegram
        data:
          title: "Birthday"
          message: "Rotam is Birthday Wish her a happy birthday"


  - alias: liran Birthday Notification
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.birthday_liran
        to: '0'
    action:
      - delay:
          hours: 8
      - service: notify.avi_telegram
        data:
          title: "Birthday"
          message: "Liran is Birthday Wish him a happy birthday"                                 


  - alias: yakir Birthday Notification
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: sensor.birthday_yakir
        to: '0'
    action:
      - delay:
          hours: 8
      - service: notify.avi_telegram
        data:
          title: "Birthday"
          message: "yakir is Birthday Wish him a happy birthday"                                 


  - alias: Reminder - Refresh date countdown sensors
    initial_state: on
    trigger:
      - platform: time
        at: '00:00:01'
      - platform: homeassistant
        event: start
    action:
      - service: python_script.date_countdown
        data:
          name: Wedding day
          type: anniversary
          date: 09/08/1994
      
      - service: python_script.date_countdown
        data:
          name: Nurit
          type: birthday
          date: 17/10/1973 

      - service: python_script.date_countdown
        data:
          name: Avi
          type: birthday
          date: 26/12/1969  
          
      - service: python_script.date_countdown
        data:
          name: Rotem
          type: birthday
          date: 16/05/1995            


      - service: python_script.date_countdown
        data:
          name: Liran
          type: birthday
          date: 25/08/1997           
  
      - service: python_script.date_countdown
        data:
          name: Yakir
          type: birthday
          date: 24/06/2004            