####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################

  - platform: kodi
    host: 192.168.1.4             
    port: 8080
    username: !secret kodi_username
    password: !secret kodi_password