    ##############
    ## שקע sh20 למצלמת שיאומי
    ###############
  - platform: mqtt
    name: "SH20 POW"
    state_topic: "stat/sh20/POWER"
    command_topic: "cmnd/sh20/POWER"
    availability_topic: "tele/sh20/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true



    ##############
    ## ac yakir
    ###############
  - platform: mqtt
    name: "AC Yakir"
    state_topic: "stat/ac_yakir/POWER"
    command_topic: "cmnd/ac_yakir/POWER"
    availability_topic: "tele/ac_yakir/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  