    ##############
    ## שקע sh20 למצלמת שיאומי
    ###############
  - platform: mqtt
    name: "SH20 POW"
    state_topic: "stat/sh20/POWER"
    command_topic: "cmnd/sh20/POWER"
    availability_topic: "tele/sh20/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

    ##############
    ## לתריס החשמלי
    ###############
  - platform: mqtt
    name: "tris up"
    state_topic: "stat/tris/POWER1"
    command_topic: "cmnd/tris/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false  
    
  - platform: mqtt
    name: "tris down"
    state_topic: "stat/tris/POWER2"
    command_topic: "cmnd/tris/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

    
    ##############
    ## ac yakir
    ###############
  - platform: mqtt
    name: "AC Yakir"
    state_topic: "stat/ac_yakir/POWER"
    command_topic: "cmnd/ac_yakir/POWER"
    availability_topic: "tele/ac_yakir/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  